name: Gerar APK Diário da Joana

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixando o código
        uses: actions/checkout@v4

      - name: 🐍 Configurando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ☕ Configurando o Motor Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 Configurando o Flutter Seguro
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: 📜 Assinando a Burocracia do Android
        run: yes | flutter doctor --android-licenses

      - name: 🔍 Verificando os Arquivos (Pente Fino)
        run: ls -R

      - name: 📦 Instalando as peças da Joana
        run: pip install flet==0.25.2 requests fpdf

      - name: 🚀 Construindo o Aplicativo (Estilo Sericom)
        run: flet build apk . --verbose

      - name: 📤 Salvando o APK Pronto!
        uses: actions/upload-artifact@v4
        with:
          name: Diario-da-Joana-APK
          path: build/apk/**/*.apk
          
